server {
    listen 80;
    # listen [::]:80;
    server_name jurnal-teknik.edu;
    root /path/to/project/jurnalteknik/jurnal-3.3; # Update this path
    index index.html index.htm index.php;
    
    location ~ /.well-known {
        allow all;
    }
    
    autoindex off;
    
    location ~ ^/ojs/cache(.*)$ {
        deny all;
    }
    
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
    
    location ~ ^/index.php($|/) {
        fastcgi_split_path_info ^(.*?\.php)(/.*)$;
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock; # Update if needed
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
    
    location ~* ^.+\.(css|js|xml|jpg|jpeg|gif|png|ico|swf|pdf|doc|xls|tiff|tif|txt|shtml|html)$ {
        access_log off;
        expires 30d;
        try_files $uri =404;
    }
    
    location ~ /\.ht {
        deny all;
    }
}
